[package]
name = "life-rs"
version = "0.1.0"
authors = ["risboo6909 <ttyv00@gmail.com"]

[dependencies]
piston_window = "0.60.*"
piston2d-opengl_graphics = "0.36.*"
find_folder = "0.3.*"
rand = "0.3.*"
time = "0.1.*"
engine = { path = "engine" }
ui = { path = "ui" }

[workspace]